// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCH2pAoOgODH6owOzwm-4T29EDsyJQkKg',
    appId: '1:869173409012:web:4d947cd8dd7cb24fb89aa1',
    messagingSenderId: '869173409012',
    projectId: 'zoom-88c67',
    authDomain: 'zoom-88c67.firebaseapp.com',
    storageBucket: 'zoom-88c67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN7Uo2SQtbrwNspGVhCQ1XJRUNzSc5gPo',
    appId: '1:869173409012:android:86b99637fe7af7b8b89aa1',
    messagingSenderId: '869173409012',
    projectId: 'zoom-88c67',
    storageBucket: 'zoom-88c67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtg7HDrp7QKydepFuBM91Kv2mubplXSHA',
    appId: '1:869173409012:ios:ec7b4b610658cfb1b89aa1',
    messagingSenderId: '869173409012',
    projectId: 'zoom-88c67',
    storageBucket: 'zoom-88c67.appspot.com',
    iosBundleId: 'com.example.videocall',
  );
}
